# Generated by Django 5.0.6 on 2024-06-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qtdInscritos', models.IntegerField()),
                ('dataEvento', models.DateField()),
                ('certificadoEvento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.certificado')),
            ],
        ),
    ]
