# Generated by Django 5.0.6 on 2024-06-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('funcao', models.BooleanField()),
                ('certificados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.certificado')),
            ],
        ),
    ]
